name: CI - Test and Lint

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Add SAM CLI installation
      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.143.0
          
      # pip cache
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 . --show-source --statistics

      - name: Run unit tests with pytest
        run: |
          pytest tests/

      - name: SAM Build
        run: |
          sam build
